openapi: 3.0.0
info:
  title: 'WebSocket Api'
  description: 'WebSocket Api Doc'
  contact:
    email: evondu1991@163.com
  version: '0.1'
paths:
  /count:
    get:
      tags:
        - WebSocket
      summary: 连接数量
      description: 获取当前WebSocket客户端的连接数量
      responses:
        default:
          description: 返回结果
  /clients:
    get:
      tags:
        - WebSocket
      summary: 连接列表
      description: 获取所有注册过的客户端列表
      responses:
        default:
          description: 返回结果
  /publish:
    post:
      tags:
        - WebSocket
      summary: 广播信息
      description: 向所有WebSocket客户端发送信息
      requestBody:
        required: true
        content:
          application/json: {  }
      responses:
        default:
          description: 返回结果
tags:
  -
    name: WebSocket
    description: WebSocket
