openapi: 3.0.0
info:
  title: 'WebSocket Api'
  description: 'WebSocket Api Doc'
  contact:
    email: evondu1991@163.com
  version: '0.1'
paths:
  /count:
    get:
      tags:
        - Base
      summary: 连接数量
      description: 获取当前WebSocket客户端的连接数量
      responses:
        default:
          description: 返回结果
  /publish:
    post:
      tags:
        - Base
      summary: 发布信息
      description: 向所有WebSocket客户端发送信息
      parameters:
        -
          name: message
          in: query
          description: 信息内容
          required: true
          schema:
            type: string
            default: 测试信息
      responses:
        default:
          description: 返回结果
  /clients:
    get:
      tags:
        - Extend
      summary: 连接列表
      description: 获取所有注册过的客户端列表
      responses:
        default:
          description: 返回结果
  /events:
    post:
      tags:
        - Extend
      summary: 发布事件
      description: 向所有登录的WebSocket客户端发布事件信息
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                event:
                  description: 事件名称
                  type: string
                  default: publish
                to:
                  description: 目标编号
                  type: string
                data:
                  description: 信息内容
                  type: string
                  default: 'sample data'
              type: object
      responses:
        default:
          description: 返回结果
tags:
  -
    name: Base
    description: 基础
  -
    name: Extend
    description: 扩展
